# Generated by Django 5.0.2 on 2024-02-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutTrackerAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='completedDate',
            field=models.DateField(default=None, null=True),
        ),
    ]
