# Generated by Django 5.0.2 on 2024-04-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutTrackerAPI', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='exercisetype',
            name='muscleGroups',
            field=models.ManyToManyField(to='WorkoutTrackerAPI.musclegroup'),
        ),
    ]
