# Generated by Django 5.0.2 on 2024-04-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutTrackerAPI', '0003_musclegroup_exercisetype_musclegroups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisetype',
            name='muscleGroups',
            field=models.ManyToManyField(related_name='muscleGroups', to='WorkoutTrackerAPI.musclegroup'),
        ),
    ]
