# Generated by Django 5.0.2 on 2024-04-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutTrackerAPI', '0004_alter_exercisetype_musclegroups'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
