# Generated by Django 5.0.4 on 2024-05-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutTrackerAPI', '0005_workoutplan_enddate_workoutplan_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisetype',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='session',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
